# 配置農作物
crops:
  - WHEAT
  - MELON
  - PUMPKIN

# 配置礦物
ores:
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE

# 配置允許使用的鎬子和挖掘時間（秒）
allowed_pickaxes:
  WOODEN_PICKAXE:
    duration: 10
    required_skill: 0
  STONE_PICKAXE:
    duration: 8
    required_skill: 10
  IRON_PICKAXE:
    duration: 6
    required_skill: 20
  GOLDEN_PICKAXE:
    duration: 4
    required_skill: 30
  DIAMOND_PICKAXE:
    duration: 2
    required_skill: 40
  NETHERITE_PICKAXE:
    duration: 1
    required_skill: 50

# 配置稀有度的機率（百分比）
rarity_chances:
  COMMON: 50
  RARE: 25
  UNCOMMON: 15
  EPIC: 7
  LEGENDARY: 3

# 配置稀有度的顏色
rarity_colors:
  COMMON: WHITE
  RARE: BLUE
  UNCOMMON: GREEN
  EPIC: LIGHT_PURPLE
  LEGENDARY: GOLD

# 配置礦物的中文名稱
ore_names:
  COAL_ORE: "煤礦"
  IRON_ORE: "鐵礦"
  GOLD_ORE: "金礦"

# 配置農作物的中文名稱
crop_names:
  WHEAT: "小麥"
  MELON: "西瓜"
  PUMPKIN: "南瓜"