name: Customfarm
version: ${project.version}
main: com.johnson.customfarm.Customfarm
api-version: 1.20
commands:
  skill:
    description: 管理玩家熟練度的指令
    usage: /<command>
    permission: customfarm.skill
    permission-message: 你沒有權限使用此指令